#!/usr/bin/env python3
"""
StegDB: Ingest repo metadata from meta/files.jsonl across StegVerse

This script scans for metadata files generated by per-repo validators
(e.g., CosDen's tools/validate_cosden_structure.py) and aggregates them
into a single JSONL index inside StegDB.

Usage (from StegDB repo root):

    python tools/ingest_repo_metadata.py

Optional:

    python tools/ingest_repo_metadata.py --search-root ../

What it does:
- Searches for **meta/files.jsonl** in sibling repos (by default: ..)
- Reads each JSONL line (one per file in that repo)
- Adds some derived fields (e.g., discovered_from path)
- Writes a unified JSONL:

    meta/aggregated_files.jsonl
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Dict, Any


STEGBDB_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SEARCH_ROOT = STEGBDB_ROOT.parent  # typically where sibling repos live

AGGREGATE_META_DIR = STEGBDB_ROOT / "meta"
AGGREGATE_META_FILE = AGGREGATE_META_DIR / "aggregated_files.jsonl"


def find_metadata_files(search_root: Path) -> List[Path]:
    """
    Find all meta/files.jsonl under the given search_root.

    We assume each participating repo writes its own:
        <repo>/meta/files.jsonl
    """
    matches: List[Path] = []
    for path in search_root.rglob("files.jsonl"):
        if path.name == "files.jsonl" and path.parent.name == "meta":
            matches.append(path)
    return matches


def ingest_metadata_file(path: Path) -> List[Dict[str, Any]]:
    """
    Read a meta/files.jsonl file and return a list of parsed records.
    """
    records: List[Dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError as exc:
                print(f"⚠️ Skipping invalid JSON line in {path}: {exc}", file=sys.stderr)
                continue
            records.append(obj)
    return records


def aggregate_all_metadata(search_root: Path) -> int:
    """
    Aggregate all found meta/files.jsonl into AGGREGATE_META_FILE.
    Returns the number of records written.
    """
    AGGREGATE_META_DIR.mkdir(exist_ok=True)
    if AGGREGATE_META_FILE.exists():
        AGGREGATE_META_FILE.unlink()

    discovered_files = find_metadata_files(search_root)
    if not discovered_files:
        print(f"⚠️ No meta/files.jsonl files found under {search_root}")
        return 0

    print(f"🔍 Found {len(discovered_files)} metadata file(s):")
    for p in discovered_files:
        print(f"   - {p}")

    now = datetime.now(timezone.utc).isoformat()
    total_records = 0

    with AGGREGATE_META_FILE.open("w", encoding="utf-8") as out:
        for meta_path in discovered_files:
            repo_root = meta_path.parent.parent  # assume: <repo>/meta/files.jsonl
            repo_name = repo_root.name

            records = ingest_metadata_file(meta_path)
            for rec in records:
                # enrich / normalize
                rec_out = dict(rec)
                rec_out.setdefault("repo", repo_name)
                rec_out["aggregated_at"] = now
                rec_out["discovered_from"] = str(meta_path.relative_to(search_root))

                out.write(json.dumps(rec_out) + "\n")
                total_records += 1

    return total_records


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Ingest StegVerse repo metadata into StegDB."
    )
    parser.add_argument(
        "--search-root",
        type=str,
        default=str(DEFAULT_SEARCH_ROOT),
        help=(
            "Root directory to search for meta/files.jsonl. "
            "Default: parent of StegDB repo."
        ),
    )
    return parser.parse_args()


def main() -> None:
    print("\n📦 StegDB Metadata Ingest\n")

    args = parse_args()
    search_root = Path(args.search_root).resolve()

    print(f"🔎 Searching for repo metadata under: {search_root}")

    count = aggregate_all_metadata(search_root)

    if count == 0:
        print("⚠️ No records aggregated. Check that validators have been run in repos.")
    else:
        rel = AGGREGATE_META_FILE.relative_to(STEGBDB_ROOT)
        print(f"\n✅ Aggregated {count} record(s) into {rel}")

    print("\nDone.\n")


if __name__ == "__main__":
    main()
